# Generated by Django 3.1.7 on 2021-02-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Контент'),
        ),
    ]
