# Generated by Django 3.1.7 on 2021-02-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commentator_name',
            field=models.CharField(default='None', max_length=50, verbose_name='Имя комментатора'),
        ),
    ]
